# Generated by Django 3.2 on 2021-07-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fm_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_height', models.CharField(max_length=50)),
                ('shirt_width', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered', models.BooleanField(default=False)),
                ('customerFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='measurementFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailor.measurements'),
        ),
    ]
