# Generated by Django 3.2 on 2021-07-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0002_auto_20210718_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurements',
            old_name='cutomerFK',
            new_name='customerFK',
        ),
    ]
