# Generated by Django 3.2 on 2021-07-18 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0003_rename_cutomerfk_measurements_customerfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_ordered',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='numberofsuits',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
