# Generated by Django 3.2 on 2021-07-18 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0004_auto_20210718_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='customerFK',
        ),
        migrations.AddField(
            model_name='customer',
            name='measurementsFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tailor.measurements'),
            preserve_default=False,
        ),
    ]
