# Generated by Django 3.2 on 2021-07-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0005_auto_20210718_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='measurementsFK',
        ),
        migrations.AddField(
            model_name='customer',
            name='shirt_height',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='shirt_width',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='measurements',
        ),
    ]
