# Generated by Django 3.2 on 2021-07-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0006_auto_20210718_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='modified',
            field=models.DateField(auto_now=True),
        ),
    ]
