# Generated by Django 3.2 on 2021-07-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0007_order_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
